export function getBanner({ name = '', version = '' } = {}) {
  return [
    `本文件${name ? `由 ${name}${version ? `@${version}` : ''} ` : ''
    }自动生成，请不要手动修改`,
    `This file is automatically generated${name ? ` by ${name}${version ? `@${version}` : ''}` : ''
    } and should not be changed by hand`
  ].join('\n')
}