import { OpenAPI, OpenAPI2, OpenAPI3 } from "@/types/openapi"
import { dirname, relative } from "path"
import { name, version } from "~/package.json"

const BANNER = `This file is automatically generated by ${name}@${version} and should not be changed by hand.`

export function getCommentMultiLine(text: string[] | string, { trim = false } = {}) {
  text = Array.isArray(text) ? text : [text]
  text = text.map(item => item.split('\n')).flat()
  const middle = text.map(item => ` * ${item}`).join('\n')
  if (trim) return middle
  return `/**\n${middle}\n */`
}



export function patchBanner(content: string, banner: string = BANNER): string {
  return `${getCommentMultiLine([banner])}\n\n${content}`
}

export function isOpenAPI2(openapi: OpenAPI): openapi is OpenAPI2 {
  return !!(openapi as OpenAPI2).swagger
}

 export function isOpenAPI3(openapi: OpenAPI): openapi is OpenAPI3 {
  return !!(openapi as OpenAPI3).openapi
}

export function getImportRelative(current: string, target: string) {
  const raw = relative(dirname(current), target)
  return raw.startsWith('../') ? raw : `./${raw}`
}